name: CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libmupdf-dev
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build native module
        run: npm run build
      
      - name: Run tests
        run: npm test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          brew install mupdf-tools
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build native module
        run: npm run build
      
      - name: Run tests
        run: npm test

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install MuPDF
        run: |
          # Download and install MuPDF development files
          # This is simplified - actual implementation would need proper MuPDF setup
          echo "MuPDF installation on Windows requires manual setup"
      
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build native module
        run: npm run build
        continue-on-error: true  # Windows build might fail without proper MuPDF setup
      
      - name: Run tests
        run: npm test
        continue-on-error: true